name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v3
        with:
          verbosity: Diagnostic

      - uses: actions/upload-artifact@v4
        with:
          name: nuget packages
          path: ./BepInEx.AssemblyPublicizer*/bin/Release/*.nupkg

      - name: Push NuGet package
        if: github.ref_type == 'tag'
        run: |
          dotnet nuget push ./BepInEx.AssemblyPublicizer*/bin/Release/*.nupkg --source ${{ secrets.NUGET_SOURCE }} --api-key ${{ secrets.NUGET_KEY }}
